### ISSUE TITLE
Sometimes a ghost isn't spectated when I click on it in the leaderboard.

### ISSUE THREAD

**Issue by Valteur** [XertroV/tm-ghosts-plus-plus#1]
I click on a ghost in the leaderboard and sometimes I don't see it.

A workaround is to manually change the time in the ghost scrubber.

Replay: https://youtu.be/0Z7n89U9LBc

**Comment by Valteur** [comment]
Another streamer (Lars) with the same bug: https://clips.twitch.tv/TemperedDiligentLouseAMPEnergy-CF7yCxcvYmaerMk3

Also another issue: clicking on eyes of enabled ghosts in the leaderboard on the left doesn't remove them. (That's why they talk about map resets in the clip.)

**Comment by XertroV** [comment]
I am having trouble replicating the not-auto-spectating bug (where you have to restart the run or change the scrubber time to show the ghost). Not sure if it still exists in the current version.

WRT toggling ghosts, this should work much better in the latest version.

Can you let me know if the latest version has solved the not-auto-spectating thing for you?

**Comment by Valteur** [comment]
I still have the not-auto-spectating problem. But I only need to fix it once per session now. Looking at the log though, I have some information:

I'm getting this yellow message:
![2023-10-16 16_32_03058632](https://github.com/XertroV/tm-ghosts-plus-plus/assets/87531948/9ef4684f-83cb-4b5f-a011-fb252e2fc234)
when the bug appears.

I'm getting this yellow message:
![2023-10-16 16_30_58058631](https://github.com/XertroV/tm-ghosts-plus-plus/assets/87531948/d71e3521-3582-4b11-ad40-3c7e84cf1e73)
when the bug gets fixed.

**Comment by Valteur** [comment]
I can confirm that 0.3.3 has fixed this for me.
