### ISSUE TITLE
PB ghost doesn't respawn with me when driving

### ISSUE THREAD

**Issue by Zehirmahn** [XertroV/tm-ghosts-plus-plus#10]
Hi thanks for this very neat ghost viewer, however I have an issue : 
my PB ghost doesn't respawn when I respawn, so I have to disable the plugin while driving.
Any idea what I could do to avoid that?
Thanks

**Comment by Zehirmahn** [comment]
It's fixed with 0.3.6, thank you!

**Comment by XertroV** [comment]
@Zehirmahn you reopened this -- is it still an issue?

**Comment by Zehirmahn** [comment]
Yes it is. Am I the only one having this? In this case I could try to re re-install the game.

**Comment by XertroV** [comment]
> Am I the only one having this? In this case I could try to re re-install the game.

It's hard to know, can you record a clip of it happening? Also how are you playing the map? (TOTD Campaign, playing a local map, via plugin, etc)

I can't replicate it.

As a workaround, you might find [ghost sync](https://openplanet.dev/plugin/ghostsync) fixes the issue for you. (Not a great workaround, but if it's a real problem that should work at least)

**Comment by Zehirmahn** [comment]
Thanks for "ghost sync"! It works well if I'm not too late at the CP :
I have to stay in "Sync to No-Respawn time" mode, because in "Sync to Checkpoints" mode the PB ghost is completely gone (even when Ghost++ is disabled).

A clip : https://drive.google.com/file/d/1iD2h7sgT1k6XhCh-bwHTCI1mSLWr-v8c/view?usp=drive_link
I tested it on a fresh Windows & game install in solo TOTD and solo campaign map 1.

**Comment by Zehirmahn** [comment]
In Local (downloaded) maps, "Sync to Checkpoints" mode works for ghost sync (but ghost++ alone doesn't)
