### ISSUE TITLE
pause button wrong side + no steering % + closing ghosts

### ISSUE THREAD

**Issue by rockskater89** [XertroV/tm-ghosts-plus-plus#2]
My homies agree play/pause button belongs on the left. Also it doesn't use dashboard and there's no setting to show steering % which would be nice. Also also ghosts take 2 attempts to close after watching.

Keep up the good work, thanks.

**Comment by XertroV** [comment]
> Also also ghosts take 2 attempts to close after watching.

This is with the latest version, right? I think I can fix it but takes a bit more fiddling with that code. The reason it's hard is that I can update *some* state for the records UI but not all of it. I can probs solve this by monitoring loaded ghosts and toggling it again if it doesn't toggle off.

> My homies agree play/pause button belongs on the left

But then the play button would be between the reset and step back buttons, and the step forward button would be all alone (unless I moved them all).

Do you have an idea on what order of buttons would work best?

**Comment by XertroV** [comment]
I made a PR to dashboard so it can be told which ghost to spectate -- if that gets pulled and dashboard gets updated then I can enable that and it'll do full dashboard integration. 

Fixed ghosts taking 2 attempts to close in next version. 

Added an option to swap the pause and reset ghosts button.
