### ISSUE TITLE
Missing options in settings to set size of main window

### ISSUE THREAD

**Issue by adrien-code-it** [XertroV/tm-ghosts-plus-plus#23]
Unless I'm missing something in the settings of `ghosts++`, the main widget (`main window` where to load ghosts and see current ghosts) is always resized to default size.

Eg, I set the widget like that on my screen:
![image](https://github.com/XertroV/tm-ghosts-plus-plus/assets/94184205/750966de-3508-4b4a-914b-077790b38aec)

When i launch any other track, it's been reset to default size (X/Y pos is saved, though):
![image](https://github.com/XertroV/tm-ghosts-plus-plus/assets/94184205/006a0416-b490-4d53-b379-38b0d33a621e)

Minor request, but it's a bit annoying ; )

**Comment by XertroV** [comment]
Fixed, it won't reset that window size anymore

**Comment by adrien-code-it** [comment]
@XertroV  thanks a lot !
